DET_FIREBASE_API_KEY = "AIzaSyAKnJmHgohOKCQudNt4tWNhsioiz3UW8IM";
DET_FIREBASE_AUTH_DOMAIN = "YOUR-PROJECT-NAME.firebaseapp.com";
DET_FIREBASE_DATABASE_URL =
  "https://daily-expense-5cc43-default-rtdb.firebaseio.com";
DET_FIREBASE_PROJECT_ID = "daily-expense-5cc43";
DET_FIREBASE_STORAGE_BUCKET = "daily-expense-5cc43.appspot.com";
DET_FIREBASE_MESSAGING_SENDER_ID = "YOUR-PROJECT-SENDER-ID";
DET_FIREBASE_APP_ID = "1:733353459239:ios:9bc90d24d2f043f00dd802";
